"""
Model quality assessment for 3D protein structures.

This module provides quality scoring functions and threshold-based filtering
for 3D protein models generated by MODELLER or other modeling tools.
"""

import subprocess
from path import Path


def external_command(arguments, name):
    """
    Execute external quality assessment program.
    
    Runs external programs like VoroMQA for model quality scoring
    with proper error handling and output capture.
    
    Args:
        arguments (list): Command-line arguments for external program
        name (str): Job name for error reporting
        
    Returns:
        subprocess.CompletedProcess: Process result with stdout/stderr
        
    Raises:
        RuntimeError: If external program fails or returns non-zero exit code
    """
    proc = subprocess.run(
        arguments,
        check=False,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE
    )

    if proc.returncode:
        raise RuntimeError("Error processing job '{}':\n{}\n".format(
            name, proc.stderr.decode("UTF-8")))

    return proc


class BaseComparison:
    """
    Base class for quality score comparisons.
    
    Provides the interface for threshold-based quality assessments
    used to accept or reject 3D models based on scoring functions.
    
    Attributes:
        cutoff (float): Threshold value for comparison
    """
    
    def __init__(self, cutoff):
        """
        Initialize comparison with threshold value.
        
        Args:
            cutoff (float): Threshold value for quality assessment
        """
        self.cutoff = cutoff

    def __call__(self, value):
        """
        Compare score value against threshold (abstract method).
        
        Args:
            value (float): Quality score to evaluate
            
        Returns:
            bool: True if model passes quality threshold
            
        Raises:
            NotImplementedError: If not implemented by subclass
        """
        raise NotImplementedError()


class HigherThan(BaseComparison):
    """
    Quality comparison for scores where higher values are better.
    
    Used for quality metrics like VoroMQA where higher scores
    indicate better model quality.
    """
    
    def __call__(self, value):
        """
        Check if score exceeds minimum threshold.
        
        Args:
            value (float): Quality score to evaluate
            
        Returns:
            bool: True if score is higher than cutoff
        """
        return value > self.cutoff


class LowerThan(BaseComparison):
    """
    Quality comparison for scores where lower values are better.
    
    Used for quality metrics like DOPE scores where lower values
    indicate better model quality.
    """
    
    def __call__(self, value):
        """
        Check if score is below maximum threshold.
        
        Args:
            value (float): Quality score to evaluate
            
        Returns:
            bool: True if score is lower than cutoff
        """
        return value < self.cutoff


class ModelQualityChecker:
    """
    Comprehensive model quality assessment system.
    
    This class orchestrates multiple quality scoring functions and applies
    threshold-based filtering to accept or reject 3D models. It supports
    both internal scores (from MODELLER) and external programs (VoroMQA).
    
    Attributes:
        cutoff (dict): Mapping of score names to comparison functions
        scorers (list): List of external scoring programs
    """
    
    def __init__(self):
        """Initialize quality checker with empty configuration."""
        self.cutoff = {}
        self.scorers = []

    def enable_scorer(self, name, program):
        """
        Enable external quality scoring program.
        
        Args:
            name (str): Scorer name (e.g., "voromqa")
            program (str): Path to external program executable
            
        Raises:
            ValueError: If scorer name is not recognized
        """
        if name == "voromqa":
            self.scorers.append(VoroMQA(program))
        else:
            raise ValueError("Invalid scorer: {}".format(name))

    def add_cutoff(self, name, comparison):
        """
        Add quality threshold for a scoring function.
        
        Args:
            name (str): Score name (e.g., "norm_dope", "voromqa")
            comparison (BaseComparison): Comparison function with threshold
        """
        self.cutoff[name] = comparison

    def add_lower_cutoff(self, name, cutoff):
        """
        Add threshold where lower scores are better.
        
        Convenience method for scores like DOPE where lower values
        indicate better model quality.
        
        Args:
            name (str): Score name
            cutoff (float): Maximum acceptable score
        """
        self.add_cutoff(name, LowerThan(cutoff))

    def add_higher_cutoff(self, name, cutoff):
        """
        Add threshold where higher scores are better.
        
        Convenience method for scores like VoroMQA where higher values
        indicate better model quality.
        
        Args:
            name (str): Score name
            cutoff (float): Minimum acceptable score
        """
        self.add_cutoff(name, HigherThan(cutoff))

    def run(self, job_data):
        """
        Assess quality of all models and apply filtering thresholds.
        
        This method:
        1. Runs external scoring programs on each model
        2. Applies all configured quality thresholds
        3. Marks models as rejected if they fail any threshold
        4. Updates model scores in job data
        
        Args:
            job_data (DataContainer): Job data with modeling results
            
        Returns:
            DataContainer: Updated job data with quality assessments
        """
        for model in job_data.modeling.models:
            # Run external quality scorers
            for scorer in self.scorers:
                value = scorer(job_data.job_dir / model.pdb)
                model.scores[scorer.name] = value

            # Apply all quality thresholds
            accepted = True
            for name, comparison in self.cutoff.items():
                accepted = accepted and comparison(model.scores[name])

            # Mark model for rejection if it fails quality checks
            model.rejected = not accepted

        return job_data


class VoroMQA:
    """
    VoroMQA model quality assessment scorer.
    
    Implements interface to the VoroMQA program for assessing 3D model
    quality using Voronoi tessellation-based analysis.
    
    Attributes:
        name (str): Scorer identifier for database storage
        program (str): Path to VoroMQA executable
    """
    
    name = "voromqa"

    def __init__(self, program):
        """
        Initialize VoroMQA scorer.
        
        Args:
            program (str): Path to VoroMQA executable
        """
        self.program = program

    def __call__(self, model_pdb):
        """
        Calculate VoroMQA quality score for a model.
        
        Executes VoroMQA program on the specified PDB file and extracts
        the global quality score from the output.
        
        Args:
            model_pdb (Path): Path to model PDB file
            
        Returns:
            float: VoroMQA quality score (higher is better)
        """
        command = [
            self.program,
            "--processors", "1",  # Single-threaded execution
            "-i", str(model_pdb)
        ]

        process = external_command(command, "voromqa")
        
        # Extract score from VoroMQA output format
        # Output format: "filename score"
        return float(process.stdout.decode().split()[1])
